# -*- coding: utf-8 -*-
"""amazon_one_plus_reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yKnxZhvXfDPGzg29L7XTFrxdrbRXFqhr
"""

# This code imports the warnings module and suppresses the display of warnings generated during script execution
import warnings
warnings.simplefilter(action='ignore', category=Warning)

import pandas as pd

# Load the dataset from a JSON URL into a pandas DataFrame
amazon_one_plus_reviews_db = pd.read_json('https://query.data.world/s/eke656w4udxnc6v57negepzxrddrzw?dws=00000')

# List the columns of the DataFrame to understand its structure
list(amazon_one_plus_reviews_db.columns)

# Drop columns that are not needed for analysis to simplify the DataFrame
amazon_one_plus_reviews_db.drop([
    'profile_name',
    'total_comments',
    'url',
    'crawled_at',
    '_id',
    'color',
    'style_name',
    'images',
    'size_name'
  ], axis=1, inplace=True)

amazon_one_plus_reviews_db

# Check for any null values in each column to ensure data quality
for column_name in amazon_one_plus_reviews_db.columns.tolist():
  print(amazon_one_plus_reviews_db[column_name].isnull().any())

# Clean the 'product' column by removing any text after '(' to standardize product names
for i in range(len(amazon_one_plus_reviews_db['product'])):
  amazon_one_plus_reviews_db['product'][i] = amazon_one_plus_reviews_db['product'][i].split('(')[0]

amazon_one_plus_reviews_db

# Trim leading and trailing whitespace from 'review_title' column values
for i in range(len(amazon_one_plus_reviews_db['review_title'])):
  amazon_one_plus_reviews_db['review_title'][i] = amazon_one_plus_reviews_db['review_title'][i].strip()

amazon_one_plus_reviews_db

# Convert 'review_rating' from string to float, keeping only the numeric part before "out"
for i in range(len(amazon_one_plus_reviews_db['review_rating'])):
  amazon_one_plus_reviews_db['review_rating'][i] = float(amazon_one_plus_reviews_db['review_rating'][i].split('out')[0])

# Ensure 'review_rating' column is of float type
amazon_one_plus_reviews_db['review_rating'] = amazon_one_plus_reviews_db['review_rating'].astype(float)

amazon_one_plus_reviews_db

# Remove newline characters from 'review_text' to clean the text
for i in range(len(amazon_one_plus_reviews_db['review_text'])):
  amazon_one_plus_reviews_db['review_text'][i] = amazon_one_plus_reviews_db['review_text'][i].replace('\n', '')

amazon_one_plus_reviews_db

# Install the word2number package, required for converting textual number expressions to numeric form
!pip install word2number

from word2number import w2n

# Clean 'helpful_count' by converting word-based numbers and removing commas
for i in range(len(amazon_one_plus_reviews_db['helpful_count'])):
  new_value = amazon_one_plus_reviews_db['helpful_count'][i].split()[0].replace(',', '')

  try: # First, try to convert directly to int
      new_value = int(new_value)

  except ValueError: # If direct conversion fails, try to convert from words

      try:
          new_value = w2n.word_to_num(new_value)

      except ValueError: # If both conversions fail, assign NA
          new_value = pd.NA

  amazon_one_plus_reviews_db['helpful_count'][i] = new_value

# Ensure 'helpful_count' column is of integer type
amazon_one_plus_reviews_db['helpful_count'] = amazon_one_plus_reviews_db['helpful_count'].astype(int)

amazon_one_plus_reviews_db

# Trim whitespace from 'review_country' values
for i in range(len(amazon_one_plus_reviews_db['review_country'])):
  amazon_one_plus_reviews_db['review_country'][i] = amazon_one_plus_reviews_db['review_country'][i].strip()

amazon_one_plus_reviews_db

# Convert 'verified_purchase' from string to binary numeric values, where 'na' becomes 0 and all other values become 1
for i in range(len(amazon_one_plus_reviews_db['verified_purchase'])):
  current_value = amazon_one_plus_reviews_db['verified_purchase'][i]

  if current_value == 'na':
    amazon_one_plus_reviews_db['verified_purchase'][i] = 0
  else:
    amazon_one_plus_reviews_db['verified_purchase'][i] = 1

# Ensure 'verified_purchase' column is of integer type
amazon_one_plus_reviews_db['verified_purchase'] = amazon_one_plus_reviews_db['verified_purchase'].astype(int)

amazon_one_plus_reviews_db

# Check data types of all columns for confirmation
amazon_one_plus_reviews_db.dtypes

# Combine 'review_title' and 'review_text' into a single 'review_description' column, formatted with tags <t> for 'title' and <b> for 'body'
review_descripiton = []
for i in range(len(amazon_one_plus_reviews_db['review_title'])):
  review_title_elem = amazon_one_plus_reviews_db['review_title'][i]
  review_text_elem = amazon_one_plus_reviews_db['review_text'][i]
  new_elem = f'<t>{review_title_elem}</t><b>{review_text_elem}</b>' # t -> title | b -> body
  review_descripiton.append(new_elem)

amazon_one_plus_reviews_db['review_descripiton'] = review_descripiton

# Drop the now redundant 'review_title' and 'review_text' columns
amazon_one_plus_reviews_db.drop(['review_title', 'review_text'], axis=1, inplace=True)

amazon_one_plus_reviews_db

# Check for any null values again after transformations
for column_name in amazon_one_plus_reviews_db.columns.tolist():
  print(amazon_one_plus_reviews_db[column_name].isnull().any())

# Rename columns
amazon_one_plus_reviews_db.columns = ['product_name', 'product_company', 'review_rating', 'review_thumbsup_count', 'review_country', 'review_date', 'is_verfied_purchase', 'product_category', 'product_sub_category', 'review_descripiton']

# Reorder columns
new_order = ['product_name', 'product_company', 'review_descripiton', 'review_rating', 'review_thumbsup_count', 'review_country', 'review_date', 'is_verfied_purchase', 'product_category', 'product_sub_category']
amazon_one_plus_reviews_db = amazon_one_plus_reviews_db[new_order]

amazon_one_plus_reviews_db

"""`amazon_one_plus_reviews_db` is ready to be loaded."""

# Export the cleaned DataFrame to a JSON file
from google.colab import files

json_str = amazon_one_plus_reviews_db.to_json(orient='records')

with open('amazon_one_plus_reviews.json', 'w') as f:
    f.write(json_str)

# Download the JSON file to your local machine
files.download('amazon_one_plus_reviews.json')