# -*- coding: utf-8 -*-
"""amazon_ecommerce_sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2wdUBWEWbo44hlz9YRY32NBGL15aXFx
"""

# This code imports the warnings module and suppresses the display of warnings generated during script execution
import warnings
warnings.simplefilter(action='ignore', category=Warning)

import pandas as pd

# Load the dataset from a data.world URL into a pandas DataFrame
amazon_ecommerce_sample_db = pd.read_csv('https://query.data.world/s/kpd37xmqr3xrxjaodwjbo5deefywvo?dws=00000')

# Listing the columns in the DataFrame
list(amazon_ecommerce_sample_db.columns)

# Dropping unnecessary columns from the DataFrame
amazon_ecommerce_sample_db.drop([
  'uniq_id',
  'number_available_in_stock',
  'number_of_reviews',
  'number_of_answered_questions',
  'average_review_rating',
  'customers_who_bought_this_item_also_bought',
  'description',
  'product_information',
  'product_description',
  'items_customers_buy_after_viewing_this_item',
  'customer_questions_and_answers'
], axis=1, inplace=True)

amazon_ecommerce_sample_db

# Checking for missing values in each column
for column_name in amazon_ecommerce_sample_db.columns.tolist():
  print(amazon_ecommerce_sample_db[column_name].isnull().any())

# Counting null values in specific columns
[
    amazon_ecommerce_sample_db['manufacturer'].isnull().sum(),
    amazon_ecommerce_sample_db['price'].isnull().sum(),
    amazon_ecommerce_sample_db['amazon_category_and_sub_category'].isnull().sum(),
    amazon_ecommerce_sample_db['customer_reviews'].isnull().sum(),
    amazon_ecommerce_sample_db['sellers'].isnull().sum()
]

# Dropping rows with missing values in critical columns
amazon_ecommerce_sample_db.dropna(subset=['manufacturer'], inplace=True)
amazon_ecommerce_sample_db.dropna(subset=['amazon_category_and_sub_category'], inplace=True)
amazon_ecommerce_sample_db.dropna(subset=['customer_reviews'], inplace=True)

# Converting the 'sellers' column to binary format, 1 if data is present and 0 for NaN
amazon_ecommerce_sample_db['sellers'] = amazon_ecommerce_sample_db['sellers'].apply(lambda x: 0 if pd.isna(x) else 1)

# Re-checking for null values after cleanup
[
    amazon_ecommerce_sample_db['manufacturer'].isnull().sum(),
    amazon_ecommerce_sample_db['price'].isnull().sum(),
    amazon_ecommerce_sample_db['amazon_category_and_sub_category'].isnull().sum(),
    amazon_ecommerce_sample_db['customer_reviews'].isnull().sum(),
    amazon_ecommerce_sample_db['sellers'].isnull().sum()
]

amazon_ecommerce_sample_db

# Cleans and standardizes the 'product_name' column in the amazon_ecommerce_sample_db DataFrame by trimming whitespace and converting text to lowercase, applying these transformations only to non-null entries
amazon_ecommerce_sample_db['product_name'] = amazon_ecommerce_sample_db['product_name'].apply(lambda x: x.strip().lower() if x is not None else x)

amazon_ecommerce_sample_db

# Cleans and standardizes the 'manufacturer' column of the amazon_ecommerce_sample_db DataFrame by applying two transformations: removing leading and trailing spaces and converting text to lowercase
amazon_ecommerce_sample_db['manufacturer'] = amazon_ecommerce_sample_db['manufacturer'].apply(lambda x: x.strip().lower())

amazon_ecommerce_sample_db

# The first line converts the 'price' column to string type to ensure that the replace operation can be applied universally (including on non-string data types). It then removes the British Pound symbol ('£') from the price values
amazon_ecommerce_sample_db['price'] = amazon_ecommerce_sample_db['price'].astype(str).str.replace('£', '')

# This line attempts to convert the cleaned 'price' column values into numeric data type
amazon_ecommerce_sample_db['price'] = pd.to_numeric(amazon_ecommerce_sample_db['price'], errors='coerce')

# The final line explicitly converts the 'price' column to float data type
amazon_ecommerce_sample_db['price'] = amazon_ecommerce_sample_db['price'].astype(float)

amazon_ecommerce_sample_db

# Initializes two empty lists, category and sub_category, which will be used to store the main category and sub-category extracted from the amazon_category_and_sub_category column of each row in the DataFrame
category, sub_category = [], []

# Iterates over the amazon_category_and_sub_category column in the DataFrame
for i in range(len(amazon_ecommerce_sample_db['amazon_category_and_sub_category'])):

  # Attempts to split each entry in the amazon_category_and_sub_category column by the '>' character, which separates the main category from the sub-category.
  # Each split component is then cleaned (converted to lowercase and stripped of leading/trailing whitespace) and added to the corresponding list. If any error
  # occurs during this process (e.g., the entry does not contain a '>' character, or there's an index error due to missing data), the except block catches the
  # exception and appends 'other' to both lists as a fallback
  try:
    split_elem = amazon_ecommerce_sample_db['amazon_category_and_sub_category'][i].split('>')
    category.append(split_elem[0].lower().strip())
    sub_category.append(split_elem[1].lower().strip())
  except:
    category.append('other')
    sub_category.append('other')

# After processing all entries, these lines add the category and sub_category lists as new columns in the amazon_ecommerce_sample_db DataFrame, effectively storing the extracted category and sub-category information in the DataFrame
amazon_ecommerce_sample_db['category'] = category
amazon_ecommerce_sample_db['sub_category'] = sub_category

# Removes the original amazon_category_and_sub_category column from the DataFrame since its data has been split into the new category and sub_category columns. This cleans up the DataFrame by removing redundant information
amazon_ecommerce_sample_db.drop('amazon_category_and_sub_category', axis=1, inplace=True)

amazon_ecommerce_sample_db

# This code imports the warnings module and suppresses the display of warnings generated during script execution
import warnings
warnings.simplefilter(action='ignore')

# Initializes a new, empty DataFrame new_df with specified columns
columns = ['product_name', 'manufacturer', 'price', 'sellers', 'category', 'sub_category', 'new_review', 'new_rate', 'new_date']
new_df = pd.DataFrame(columns=columns)

# This loop iterates through each row of the original amazon_ecommerce_sample_db DataFrame to process and extract customer reviews
for index, row in amazon_ecommerce_sample_db.iterrows():

    # Each customer review string is split by '|' to separate individual reviews. Then, each review is further split by '//' to separate components of the review, such as the title, body, rating, and date
    customer_reviews = row['customer_reviews'].split('|')

    product_name = row['product_name']
    manufacturer = row['manufacturer']
    price = row['price']
    sellers = row['sellers']
    category = row['category']
    sub_category = row['sub_category']

    for i in range(len(customer_reviews)):

      # For each processed review, a new row is created with the relevant data fields and then added to new_df
      review = customer_reviews[i].strip().split('//')

      if len(review) >= 5:
        new_review_title = review[0].strip()
        new_review_body = review[-1].strip()
        new_review = f'<t>{new_review_title}</t><b>{new_review_body}</b>'
        new_rate = review[1].strip()
        new_date = review[2].strip()

        new_row = {
            'product_name': product_name,
            'manufacturer': manufacturer,
            'price': price,
            'sellers': sellers,
            'category': category,
            'sub_category': sub_category,
            'new_review': new_review,
            'new_rate': new_rate,
            'new_date': new_date,
        }

        new_row = pd.DataFrame([new_row])
        new_df = pd.concat([new_df, new_row], ignore_index=True)

# Updates the amazon_ecommerce_sample_db variable to reference the newly created and populated DataFrame new_df, which now contains the processed and structured review data along with the other product information
amazon_ecommerce_sample_db = new_df

amazon_ecommerce_sample_db

# This line attempts to convert the values in the 'new_rate' column of the DataFrame amazon_ecommerce_sample_db to a numeric data type
amazon_ecommerce_sample_db['new_rate'] = pd.to_numeric(amazon_ecommerce_sample_db['new_rate'], errors='coerce')

# This line removes any rows in the DataFrame amazon_ecommerce_sample_db where the 'new_rate' column contains NaN values
amazon_ecommerce_sample_db.dropna(subset=['new_rate'], inplace=True)

# This line converts the data type of the 'new_rate' column to float, ensuring that it is explicitly recognized as containing floating-point numbers
amazon_ecommerce_sample_db['new_rate'].astype(float)

amazon_ecommerce_sample_db.dtypes

# Converting 'new_date' to datetime format
amazon_ecommerce_sample_db['new_date'] = amazon_ecommerce_sample_db['new_date'].apply(lambda x: pd.to_datetime(x))

amazon_ecommerce_sample_db

amazon_ecommerce_sample_db.dtypes

from sklearn.impute import SimpleImputer
import numpy as np

# Creating a SimpleImputer object to fill missing values in 'price' column with the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Applying the imputer to the 'price' column
amazon_ecommerce_sample_db['price'] = imputer.fit_transform(amazon_ecommerce_sample_db['price'].values.reshape(-1, 1))

amazon_ecommerce_sample_db

# Checking again for missing values after imputation
for column_name in amazon_ecommerce_sample_db.columns.tolist():
  print(amazon_ecommerce_sample_db[column_name].isnull().any())

# Renaming columns
amazon_ecommerce_sample_db.columns = ['product_name', 'product_company', 'product_price', 'is_verfied_purchase', 'product_category', 'product_sub_category', 'review_descripiton', 'review_rating', 'review_date']

# Reordering the columns
new_order = ['product_name', 'product_company', 'review_descripiton', 'review_rating', 'review_date', 'is_verfied_purchase', 'product_category', 'product_sub_category', 'product_price']
amazon_ecommerce_sample_db = amazon_ecommerce_sample_db[new_order]

amazon_ecommerce_sample_db

"""`amazon_ecommerce_sample_db` is ready to be loaded."""

# Exporting the DataFrame to a JSON file for download
from google.colab import files

json_str = amazon_ecommerce_sample_db.to_json(orient='records')

with open('amazon_ecommerce_sample.json', 'w') as f:
    f.write(json_str)

# Downloading the JSON file
files.download('amazon_ecommerce_sample.json')